name: 'Bit Tag and Export'
description: 'Persist Bit Soft Tags and Export to Remote Scope'
branding: 
  icon: 'upload-cloud'
  color: 'purple'
inputs:
  ws-dir:
    description: "Workspace json file directory path"
    required: false
  persist:
    description: "Persist soft tagged components"
    required: false
  token:
    description: "Github token"
    required: false
  
runs:
  using: 'composite'
  steps:
    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: '20'
    - name: Run Bit Initialization Script
      run: node ${{ github.action_path }}/dist/index.js
      shell: bash
      env:
        WS_DIR: ${{ inputs.ws-dir }}
        GITHUB_TOKEN: ${{ inputs.token }}

