name: Test Bit Pull Request Labels
on:
  pull_request:
    types:
      - opened
      - synchronize
permissions:
  pull-requests: write
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      BIT_CONFIG_ACCESS_TOKEN: ${{ secrets.BIT_CONFIG_ACCESS_TOKEN }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Initialize Bit
        uses: bit-tasks/init@v1
        with:
            ws-dir: 'test-data'
      - name: Bit Pull Request
        uses: bit-tasks/pull-request@main
        with:
          version-labels: true
          # version-labels-color-major: 'C2E0C6'
          # version-labels-color-minor: 'C2E0C6'
          # version-labels-color-patch: 'C2E0C6'
